# Generated by Django 4.0.5 on 2022-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Sale', 'Sale')], max_length=100),
        ),
    ]
