# Generated by Django 4.0.5 on 2022-06-23 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'ordering': ['user_id'], 'verbose_name': 'orderproduct', 'verbose_name_plural': 'orederproducts'},
        ),
    ]
