# Generated by Django 4.0.5 on 2022-06-23 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_orderproduct_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='main.order'),
            preserve_default=False,
        ),
    ]
