# Generated by Django 4.0.5 on 2022-06-28 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_product_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
    ]
